### ISSUE TITLE
Anchors not working correctly

### ISSUE THREAD

**Issue by mikernet** [jbltx/DiscordFX#3]
The anchors don't appear to work correctly when tested on on Edge, Chrome, or FireFox on both your "Live Demo" page and my own doc outputs. 

When I view your live demo pages and scroll down the API documentation in Edge or Chrome, the anchors are always visible and they dont move with the page - they are stuck in their initial positions.

When I view it in FireFox they only show up on mouse over but they also don't scroll with the page.

**Comment by jbltx** [comment]
Fixed in v0.4
